/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MariposasPanel.java
 *
 * Created on 24-ene-2010, 16:17:16
 */
package view.ayuda;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Alicia
 */
public class MariposasPanel extends javax.swing.JPanel {

    /** Creates new form MariposasPanel */
    public MariposasPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(420, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {

        Dimension tamanio = getSize(); /////si usamos getsize(100,100); ponemos nuestro tamaño definido

        ImageIcon imagenfondo = new ImageIcon(getClass().getResource("image/mariposas.png"));
        g.drawImage(imagenfondo.getImage(), 0, 0, tamanio.width, tamanio.height, null);

        setOpaque(false);

        super.paintComponent(g);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
